version: "3.1"
networks:
  ghost:
services:
  ghost-app:
    image: ghost:latest
    networks:
      - ghost
    depends_on:
      - db
    ports:
      - "2368:2368"
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: mysqlroot
      database__connection__database: ghost

  nginx:
    build: nginx
    networks:
      - ghost
    depends_on:
      - ghost-app
    ports:
      - "80:80"

  db:
    image: "mysql:5.7.15"
    networks:
      - ghost
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot
    volumes:
      - $PWD/data:/var/lib/mysql
    ports:
      - "3306:3306"
