version: "3.1"
networks:
  ghost:
services:
  ghost-moka:
    build: ghost
    networks:
      - ghost
    depends_on:
      - ghost-db
    ports:
      - "2368:2368"
    environment:
      database__client: mysql
      database__connection__host: ghost-db
      database__connection__user: root
      database__connection__password: mysqlroot
      database__connection__database: ghost

  ghost-nginx:
    build: nginx
    networks:
      - ghost
    depends_on:
      - ghost-moka
    ports:
      - "3000:3000"

  ghost-db:
    build: mysql
    networks:
      - ghost
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
